<?php

//Your username.
$username = '2020-11-01';
//Your password.
$password = '3CHf7ZJfQ541';
//Generate Basic Auth String
$basicAuth = (base64_encode("$username:$password"));

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://global.whoisdatacenter.com/2020-10-11.zip');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
curl_setopt($ch, CURLOPT_VERBOSE, true);


$headers = array();
//Basic Auth
$header = sprintf("Authorization: Basic %s", $basicAuth);
$headers[] = $header;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
  echo 'Error:' . curl_error($ch);
}

$filepath="/home/sarmad/Work/file.zip";
file_put_contents($filepath, $result);
return (filesize($filepath) > 0)? true : false;
curl_close($ch);
